xcodeproj 'SLRESTfulCoreData'
workspace '../SLRESTfulCoreData'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '2.1.1'
  pod 'Expecta', '0.2.1'
end

target :ios do
  platform :ios, '5.0'
  link_with 'iOS Tests'
  import_pods
end
