xcodeproj 'SLRESTfulCoreData'
workspace '../SLRESTfulCoreData'
inhibit_all_warnings!

platform :ios, '6.0'
link_with 'iOS Tests'

pod 'OCMock', '>= 2.2'
pod 'Expecta', '>= 0.2.2'
pod 'SLRESTfulCoreData', path: '../SLRESTfulCoreData.podspec'
