xcodeproj 'SLRESTfulCoreData'
workspace '../SLRESTfulCoreData'
inhibit_all_warnings!

platform :ios, '5.0'
link_with 'iOS Tests'

pod 'OCMock', '2.2'
pod 'Expecta', '0.2.1'
pod 'SLCoreDataStack', '>= 0.2.0'
